force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>Category to assign via LWC</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CategoryAssignment__c/CategoryAssignment__c.object-meta.xml
<CustomObject>
    <description>Used to Assign a Category to a Record via LWC</description>
    <label>Category Assignment</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Category Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CategoryAssignment__c/fields/CategoryId__c.field-meta.xml
<CustomField>
    <fullName>CategoryId__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Category Assignment</relationshipLabel>
    <relationshipName>Category_Assignment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CategoryAssignment__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <label>Related Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
  public static Account createAccount() {
    return new Account(Name = 'testAcc');
  }

  public static Category__c createCategory() {
    return new Category__c(Name = 'testCategory');
  }

  public static CategoryAssignment__c createCategoryAssignment() {
    Account acc = TestDataFactory.createAccount();
    insert acc;
    Category__c cat = TestDataFactory.createCategory();
    insert cat;

    return new CategoryAssignment__c(
      RelatedRecordId__c = acc.id,
      CategoryId__c = cat.id
    );
  }

  public static CategoryAssignment__c insertCategoryAssignment() {
    CategoryAssignment__c catAssign = createCategoryAssignment();
    insert catAssign;
    return catAssign;
  }
}